Beydanca_sözlüğü={          
                            "A"and"a" :"Д",
                            "B"and"b" :"𐰝",
                            "C"and"c" :"๕",
                            "Ç"and"ç" :"Ҁ",
                            "D"and"d" :"𐰖",
                            "E"and"e" :"З",
                            "F"and"f" :"Ғ",
                            "G"and"g" :"Ә",
                            "Ğ"and"ğ" :"ق",
                            "H"and"h" :"𐱅",
                            "X"and"x" :"Җ",
                            "İ"and"i" :"Ї",
                            "J"and"j" :"𐰉",
                            "K"and"k" :"Ԟ",
                            "Q"and"q" :"Ҩ",
                            "L"and"l" :"Ŀ",
                            "M"and"m" :"𐰡",
                            "N"and"n" :"П",
                            "O"and"o" :"𐰧",
                            "Ö"and"ö" :"𐰦",
                            "P"and"p" :"ק",
                            "R"and"r" :"Ԅ",
                            "S"and"s" :"§",
                            "Ş"and"ş" :"§̧",
                            "T"and"t" :"☂",
                            "U"and"u" :"𝓤",
                            "Ü"and"ü" :"☋",
                            "Y"and"y" :"𐰠",
                            "V"and"v" :"۷",
                            "Z"and"z" :"𝕫",
                            "W"and"w" :"Ш",
                                  " " :" ",
                            "I"and"ı" :"I",
}
x=input()
for i in range(0,len(x)):
    anlamı=x[i]
    çeviri=Beydanca_sözlüğü.get(anlamı)
    print(çeviri , end="")